### PR TITLE
Add install instructions to Python readme.

### LINKED ISSUE #2: Instructions on static installation
Thank you for putting this library together!

I had to end up editing the setup file to run the -staticlib variant manually for the install. Is there a better way?

### PR DESCRIPTION
**Pull request by dom96**
Fixes #2

### CODE REVIEW

**Comment by irmen** [comment]
I'm not a huge fan of manually linking things in /usr/.. like you're suggesting, if there's a better alternative.
By which I mean installing a binaryen package from your distro's packagemanager. For example, on Manjaro/ArchLinux there is the 'binaryen' community package that installs these files for you. Can you please modify this PR to suggest this first?

**Review by irmen — CHANGES_REQUESTED** [review]
suggest installing distro package first, if available. See PR comment

**Comment by dom96** [comment]
Feel free to suggest changes and apply them, should be possible via GitHub's UI.

**Comment by irmen** [comment]
Wait, you can *edit* other author's files in a PR?

**Comment by dom96** [comment]
Yep. If you try to add a comment to a line, the editor has an option to suggest a line change. If you do that and submit the comment with the suggestion you should be able to apply that suggestions afterwards, then squash and merge the PR.

**Comment by irmen** [comment]
Well, TIL.  I have never seen or used this feature on Github yet!

**Comment by dom96** [comment]
Updated. Feel free to squash merge.

**Comment by irmen** [comment]
looks good. thanks

**Pull request merged**
